const $ = id => document.getElementById(id);

function stripComments(source) { let out='',i=0,quote=null; while(i<source.length){const c=source[i],n=source[i+1];if(quote){out+=c;if(c==='\\')out+=source[++i]||'';else if(c===quote)quote=null;i++;continue;}if(c==='"'||c==="'"){quote=c;out+=c;i++;continue;}if(c==='-'&&n==='-'){i+=2;while(i<source.length&&source[i]!=='\n')i++;if(source[i]==='\n')out+='\n';continue;}out+=c;i++;}return out; }
function encodeStrings(source) { let out='',i=0; while(i<source.length){const q=source[i];if(q!=='"'&&q!=="'"){out+=q;i++;continue;}let j=i+1,v='',closed=false;while(j<source.length){const c=source[j];if(c==='\\'){v+=c+(source[j+1]||'');j+=2;continue;}if(c===q){closed=true;break;}v+=c;j++;}if(!closed){out+=q;i++;continue;}if(v.length===0)out+='""';else if(v.length<=512){const bytes=new TextEncoder().encode(v);out+=`string.char(${Array.from(bytes).join(',')})`;}else out+=q+v+q;i=j+1;}return out; }
function renameLocals(source) { const names=new Map();let counter=0;const reserved=new Set(['self','script']);source=source.replace(/\blocal\s+([A-Za-z_][A-Za-z0-9_]*)/g,(m,n)=>{if(reserved.has(n))return m;if(!names.has(n))names.set(n,`_i${(++counter).toString(36)}`);return `local ${names.get(n)}`;});for(const [name,replacement] of names){const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');source=source.replace(new RegExp(`\\b${escaped}\\b`,'g'),replacement);}return source; }
function addJunk(source) { const a=Math.floor(Math.random()*9000)+1000,b=Math.floor(Math.random()*9000)+1000;return `local _IND_${a}=(${b}-${b})\nif _IND_${a}~=0 then return end\n`+source; }
function addIntegrity(source) { return `local _IND_MARKER=${JSON.stringify(Math.random().toString(36).slice(2,12))}\n`+source; }
function transform(source,level,options){let out=stripComments(source);if(options.rename)out=renameLocals(out);if(options.strings)out=encodeStrings(out);if(options.junk&&level!=='normal')out=addJunk(out);if(options.integrity&&level!=='normal')out=addIntegrity(out);if(level==='extreme'||level==='max')out=out.split('\n').map(x=>x.trim()).filter(Boolean).join('\n');return `-- IND OBFUSCATOR | ${level.toUpperCase()}\n${out.trim()}\n`; }
async function copyText(value,message){if(!value)return;try{await navigator.clipboard.writeText(value);}catch{const area=document.createElement('textarea');area.value=value;document.body.appendChild(area);area.select();document.execCommand('copy');area.remove();}$('status').textContent=message;}
$('copySource').onclick=()=>copyText($('payload').value,'Obfuscated source copied.');
$('obfuscate').onclick=()=>{const source=$('source').value.trim();if(!source){$('status').textContent='Paste Luau source first.';return;}const level=$('level').value;const options={rename:$('rename').checked,strings:$('strings').checked,junk:$('junk').checked,integrity:$('integrity').checked};$('obfuscate').disabled=true;$('status').textContent='Transforming locally…';try{$('payload').value=transform(source,level,options);$('status').textContent=`Done — ${level.toUpperCase()} obfuscation complete. Nothing was uploaded.`;}catch(e){$('status').textContent=e.message||'Obfuscation failed.';}finally{$('obfuscate').disabled=false;}};