const $=id=>document.getElementById(id);
const source=$('source'),status=$('status'),generate=$('generate');
function setStatus(text,error=false){status.textContent=text;status.style.color=error?'#ff8585':'#8f98aa'}
function updateCount(){$('counter').textContent=`${source.value.length.toLocaleString()} characters`}
async function copyText(value,msg){if(!value)return setStatus('Nothing to copy.',true);try{await navigator.clipboard.writeText(value)}catch{const t=document.createElement('textarea');t.value=value;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}setStatus(msg)}
$('clear').onclick=()=>{source.value='';$('loader').value='';$('rubisUrl').value='';$('fileInfo').textContent='No file selected';$('ready').textContent='WAITING';updateCount();setStatus('Cleared.')};
source.addEventListener('input',updateCount);
$('chooseFile').onclick=()=>$('luaFile').click();
$('luaFile').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;await loadFile(file)});
async function loadFile(file){const n=file.name.toLowerCase();if(!n.endsWith('.lua')&&!n.endsWith('.luau'))return setStatus('Please choose a .lua or .luau file.',true);if(file.size>5*1024*1024)return setStatus('File is too large. Maximum is 5 MB.',true);try{source.value=await file.text();$('fileInfo').textContent=`${file.name} • ${(file.size/1024).toFixed(1)} KB`;updateCount();setStatus(`Loaded ${file.name}.`)}catch(e){setStatus(`Could not read file: ${e.message||e}`,true)}}
$('copyLoader').onclick=()=>copyText($('loader').value,'Loadstring copied.');
$('copyUrl').onclick=()=>copyText($('rubisUrl').value,'Pastefy URL copied.');
generate.onclick=async()=>{const content=source.value;if(!content.trim())return setStatus('Paste or choose a Lua/Luau script first.',true);generate.disabled=true;$('loader').value='';$('rubisUrl').value='';$('ready').textContent='CREATING…';setStatus('Creating a new Pastefy paste…');try{const r=await fetch('../api/create-paste',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({content,title:(($('scriptTitle').value||'IND HUB SCRIPT').trim().slice(0,120))})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`Server error (${r.status})`);if(!data.raw_url)throw new Error('Pastefy did not return a raw URL.');$('rubisUrl').value=data.raw_url;$('loader').value=`loadstring(game:HttpGet(${JSON.stringify(data.raw_url)}))()`;$('ready').textContent='READY ✓';setStatus(`Success! New Pastefy paste created${data.id?` (${data.id})`:''}.`)}catch(e){$('ready').textContent='ERROR';setStatus(e.message||'Generation failed.',true)}finally{generate.disabled=false}};
updateCount();