const express=require('express');const crypto=require('crypto');const path=require('path');
const app=express();const PORT=process.env.PORT||3000;const PUBLIC_URL=process.env.PUBLIC_URL||`http://localhost:${PORT}`;const SECRET=process.env.PAYLOAD_SECRET||crypto.randomBytes(32).toString('hex');
const store=new Map();app.use(express.json({limit:'2mb'}));app.use(express.static(path.join(__dirname,'..')));
function id(){return crypto.randomBytes(18).toString('base64url')}function xor(data,key){const b=Buffer.from(data);const k=Buffer.from(key);for(let i=0;i<b.length;i++)b[i]^=k[i%k.length];return b.toString('base64url')}
function renameIdentifiers(src){const names=new Map();let n=0;return src.replace(/\b(local|function)\s+([A-Za-z_][A-Za-z0-9_]*)/g,(m,k,name)=>{if(!names.has(name))names.set(name,'v'+(++n).toString(36));return `${k} ${names.get(name)}`}).replace(/\b([A-Za-z_][A-Za-z0-9_]*)\b/g,m=>names.get(m)||m)}
function encodeStrings(src){return src.replace(/(['"])(.*?)\1/g,(m,q,s)=>{if(!s||s.length>300)return m;const bytes=Buffer.from(s);return `string.char(${[...bytes].join(',')})`})}
function junk(src){return `local __ind_${crypto.randomBytes(4).toString('hex')}=0\n`+src}
function transform(source,level,opt){let out=source.replace(/--[^\n]*/g,'');if(opt.rename)out=renameIdentifiers(out);if(opt.strings)out=encodeStrings(out);if(opt.junk&&level!=='normal')out=junk(out);return out.replace(/\s+$/,'')}
app.get('/api/health',(req,res)=>res.json({ok:true,name:'IND OBFUSCATOR'}));
app.post('/api/obfuscate',(req,res)=>{try{const {source,level='max',display='IND OBFUSCATOR PROTECTED LOADER',options={}}=req.body||{};if(typeof source!=='string'||source.length<1)return res.status(400).json({error:'Source is required'});if(source.length>1500000)return res.status(413).json({error:'Source too large'});const payload=transform(source,level,options);const token=id();const wrapped=xor(payload,SECRET+token);store.set(token,{payload:wrapped,created:Date.now(),display:String(display).slice(0,120)});const loader=`-- ${String(display).replace(/\n/g,' ')}\nloadstring(game:HttpGet("${PUBLIC_URL}/api/loader/${token}"))()`;res.json({loader,preview:`Stored payload: ${payload.length} bytes`})}catch(e){res.status(500).json({error:'Obfuscation failed'})}});
app.get('/api/loader/:token',(req,res)=>{const item=store.get(req.params.token);if(!item)return res.status(404).send('-- invalid or expired token');if(Date.now()-item.created>86400000){store.delete(req.params.token);return res.status(410).send('-- token expired')}try{const raw=Buffer.from(item.payload,'base64url');const key=Buffer.from(SECRET+req.params.token);for(let i=0;i<raw.length;i++)raw[i]^=key[i%key.length];store.delete(req.params.token);res.type('text/plain').send(raw.toString())}catch{res.status(500).send('-- payload error')}});
app.listen(PORT,()=>console.log(`IND OBFUSCATOR listening on ${PORT}`));